[general]
seed = 1234
device = "mps"

[data]
max_len = 1024
num_labels = 3

[model]
embedding_dim = 128
d_k = 16
d_v = 16
n_heads = 8
hidden_layers = 512
transformer_layers = 4
dropout = 0.1 
max_len = 1024
num_classes = 3

[model.rnn] 
rnn_hidden_size = 512
rnn_num_layers = 1
rnn_dropout = 0.1 

[training]
batch_size = 16 
learning_rate = 1e-4
num_epochs = 25
patience = 3
alpha = 1e-5

[training.transformer] 
epochs = 1
max_len = 512

[training.rnn]
epochs = 25
